services:
  database:
    image: postgres:16
    container_name: cv_database
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - cv_network

  cv_back:
    build: .
    container_name: cv_back_service
    ports:
      - "8000:8000"
    environment:
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_TOKEN=${VAULT_TOKEN}
      - VAULT_KV_MOUNT=${VAULT_KV_MOUNT}
      - VAULT_JWT_CV_BACK_PATH=${VAULT_JWT_CV_BACK_PATH}
      - VAULT_CV_BACK_PATH=${VAULT_CV_BACK_PATH}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
    depends_on:
      - database
    networks:
      - cv_network

volumes:
  pgdata:

networks:
  cv_network:
    driver: bridge